=== c2202lm61/xmlShopquanao/src/shop/dtdshop.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT Shop (shirt)*>
<!ELEMENT shirt (name,amount,price,description,sname)>
<!ATTLIST shirt sid ID #REQUIRED>
<!ELEMENT name (#PCDATA)> 
<!ELEMENT amount (#PCDATA)> 
<!ELEMENT price (#PCDATA)> 
<!ELEMENT description (#PCDATA)> 
<!ELEMENT sname (#PCDATA)> 
<!ENTITY shopname "APTECH shop">

=== c2202lm61/xmlShopquanao/src/shop/shop.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XMLDocument.xml to edit this template
-->
<!DOCTYPE Shop SYSTEM "dtdshop.dtd">
<Shop>
    <shirt sid="s001">
        <name>so mi</name>
        <amount>7</amount>
        <price>6.4</price>
        <description>san pham tot, dang su dung</description>
        <sname>&shopname;</sname>
    </shirt>
    <shirt sid="s002">
        <name>ao dai</name>
        <amount>8</amount>
        <price>9.4</price>
        <description>san pham tot, kieu dang dep</description>
        <sname>&shopname;</sname>
    </shirt>
    <shirt sid="s003">
        <name>ao gucci</name>
        <amount>7</amount>
        <price>12.4</price>
        <description>san pham tot, dang su dung</description>
        <sname>&shopname;</sname>
    </shirt>
    
</Shop>
