=== c2202lm61/xmlShopquanao/src/shop/xmlschema.xsd
<?xml version="1.0"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XmlSchema.xsd to edit this template
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:element name="shop" type="list"/>
    <xs:complexType name="list">
        <xs:sequence>
            <xs:element name="clother" type="clother" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="clother">
        <xs:sequence>
            <xs:element name="sid" type="xs:integer"/>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="size" type="sizeType"/>
            <xs:element name="amount" type="amountType"/>
            <xs:element name="price" type="priceType"/>
            <xs:element name="category" type="clotherType"/>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="sizeType">
        <xs:restriction base="xs:string">
            <xs:pattern value="(s|m|l|xl|xxl)"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="priceType">
        <xs:restriction base="xs:decimal">
            <xs:fractionDigits value="2"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="amountType">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="0"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="clotherType">
        <xs:restriction base="xs:string">
            <xs:pattern value="(quan|ao)"/>
        </xs:restriction>
    </xs:simpleType>
    
</xs:schema>

=== c2202lm61/xmlShopquanao/src/shop/schemashop.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XMLDocument.xml to edit this template
-->



<shop
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='file:/home/user/NetBeansProjects/Shopquanao/src/shop/xmlschema.xsd'>
    <clother>
        <sid>1</sid>
        <name>ao dai</name>
        <size>s</size>
        <amount>2</amount>
        <price>1.34</price>
        <category>ao</category>
    </clother>
    <clother>
        <sid>2</sid>
        <name>quan jein</name>
        <size>m</size>
        <amount>2</amount>
        <price>3.34</price>
        <category>quan</category>
    </clother>
    <clother>
        <sid>3</sid>
        <name>ao khoac</name>
        <size>xxl</size>
        <amount>2</amount>
        <price>4.24</price>
        <category>ao</category>
    </clother>
   
</shop>
